aliases:
  - &dep_ensure
    name: dep_ensure
    command: |
      go get -u github.com/golang/dep/cmd/dep
      dep ensure
defaults: &defaults
  working_directory: /go/src/github.com/devopsmakers/xterrafile
  docker:
    - image: circleci/golang:1.13.8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *dep_ensure
      - run:
          name: build_and_test
          command: |
            go build -v
            go test -v ./...
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: *dep_ensure
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
